<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Aco228.Common\src\Aco228.Common\Aco228.Common.csproj" />
      <ProjectReference Include="..\..\..\Aco228.v2.MongoDb\src\Aco228.v2.MongoDb\Aco228.MongoDb\Aco228.MongoDb.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.2" />
    </ItemGroup>

</Project>
